from enum import StrEnum

class LOGENTRY_KEYS(StrEnum):
    NEW_FPOINTERS = "new_fpointers"
    NEW_SIGNAL = "new_signal"
    NEW_FPOINTERS_PAYLOAD = "new_fpointers_json"
    STABLE_FPOINTERS = "stable_fpointers"
    STABLE_SIGNAL = "stable_signal"
    STABLE_FPOINTERS_PAYLOAD = "new_stable_fpointers_json"
    SAVED_ITEM = "saved_item"
    MINIMIZATION_REPORT_NO_DIFF = "minimization_result_equal"
    MINIMIZATION_REPORT_SAVE_FPOINTERS = "minimization_result_no_signal"
    MINIMIZATION_REPORT_SAVE_SIGNAL = "minimization_result_no_fpointer"
    MINIMIZATION_SPLIT = "minimization_split"
    MINIMIZATION_WHOLE_SKIP = "minimization_skip"
    MINIMIZATION_FPOINTER_SKIP = "minimization_skip_fpointer"
    MINIMIZATION_SIGNAL_SKIP = "minimization_skip_signal"
    PC_COVER = "total_cover"
    TOTAL_JOB_DURATION = "total_job_duration"
    TOTAL_PROG_EXECUTIONS = "total_test_case_executions"
    FPOINTER_PROG_EXECUTIONS = "new_test_case_executions_because_of_fpcov"
    PROG_EXECUTIONS_JOB_DURATION = "test_executions_job_duration"
    FPOINTER_PROG_EXECUTIONS_JOB_DURATION = "test_executions_because_of_fpcov_job_duration"
    PROG_EXECUTIONS_ALL_INDIVIDUAL_DURATIONS = "test_executions_individual_durations"
    PROG_EXECUTIONS_FPOINTER_INDIVIDUAL_DURATIONS = "test_executions_individual_durations_because_of_fpcov"


class RESULT_KEYS(StrEnum):
    NEW_FPOINTERS = "new_fpointers"
    NEW_SIGNAL = "new_signal"
    NEW_FPOINTERS_PAYLOAD = "new_fpointers_json"
    STABLE_FPOINTERS = "stable_fpointers"
    NEW_STABLE_FPOINTERS = "new_stable_fpointers"
    NEW_STABLE_FPOINTERS_PAYLOAD = "new_stable_fpointers_json"
    FPOINTER_PAYLOAD_FPOINTER_LOC_KEY = "StoredValueLocation"
    FPOINTER_PAYLOAD_STOREINST_LOC_KEY = "PCLocation"
    STABLE_SIGNAL = "stable_signal"
    NEW_STABLE_SIGNAL = "new_stable_signal"
    CALL_NAME = "call"
    SAVED_PROG = "prog_in_corpus"
    MINIMIZATION_RESULT = "minimization_result"
    MINIMIZATION_RES_PROG = "result_prog"
    MINIMIZATION_RES_TYPE = "type"
    PROGID = "prog_id"
    TRIAGEID = "triage_id"
    ORIGINAL_PROG = "original_prog"
    COUNT = "count"
    PC_COVER = "PC_COVER"
    TIMESTAMP = "timestamp"
    TOTAL_JOB_DURATION = "job_duration"
    TOTAL_PROG_EXECUTIONS = "prog_executions"
    FPOINTER_PROG_EXECUTIONS = "prog_executions_because_of_fpcov"
    PROG_EXECUTIONS_JOB_DURATION = "prog_executions_job_duration"
    FPOINTER_PROG_EXECUTIONS_JOB_DURATION = "prog_executions_because_of_fpcov_job_duration"
    PROG_EXECUTIONS_ALL_INDIVIDUAL_DURATIONS = "prog_executions_individual_durations"
    PROG_EXECUTIONS_FPOINTER_INDIVIDUAL_DURATIONS = "prog_executions_individual_durations_because_of_fpcov"
    TAGS = "tags"

class TAG_RESULT_VALUES(StrEnum):
    FPOINTER_ORIGIN = "fpointer_origin"

class MINIMIZATION_RESULT_VALUES(StrEnum):
    MINIMIZATION_RES_NODIFF = "signal_fpointer_equal"
    MINIMIZATION_RES_SAVE_SIGNAL = "save_signal_no_fpointer"
    MINIMIZATION_RES_SAVE_FPOINTER = "save_fpointer_no_signal"
    MINIMIZATION_RES_FPOINTER_SKIP = "skip_fpointer"
    MINIMIZATION_RES_SIGNAL_SKIP = "skip_signal"
    MINIMIZATION_SKIP = "minimization_skip"
    MINIMIZATION_SPLIT = "minimization_split"
