# This compose file is meant to mount the linux directory in the docker container 
# to compile with wllvm and run analysis.

services:
  compile_llvm:
    build:
      context: .
      dockerfile: ./build_llvm/Dockerfile
    volumes:
      - ./build_llvm/llvm-project:/home/src/llvm-project
    command: /bin/bash
    tty: true
    stdin_open: true
  
  compile_kernel:
    build:
      context: .
      dockerfile: ./build_kernel/Dockerfile
    volumes:
      - ./build_llvm/llvm-project:/home/custom_llvm
      - ./build_kernel:/home/build_kernel
      - /path/to/linux:/home/linux  
    command: /bin/bash
    tty: true
    stdin_open: true