#!/usr/bin/env python3
"""
This script allowsconsumes the json files generated by extract_func_stores.py and
extract_saved_progs.py to generate interesting data.

It takes the path to both json files as parameters and prints results to stdout.
"""

import json
import argparse
from pathlib import Path
import sys

FIRST_APPEARANCE_KEY = "first_appearance"
COUNT_KEY = "count"
FUNCTION_POINTERS_KEY = "function_pointers"
PC_KEY = "PC"
PROGID_KEY = "prog_id"
STORED_VALUE_KEY = "StoredValue"
CALL_KEY = "call"


def find_first_appearance(stored_funcs_per_prog: list[dict]) -> dict[str, dict]:
    res: dict[str, dict] = {}

    for entry in stored_funcs_per_prog:
        stored_funcs = entry[FUNCTION_POINTERS_KEY]
        for func in stored_funcs:
            key = f"{func[PC_KEY]}|{func[STORED_VALUE_KEY]}"
            if key not in res:
                value = {PROGID_KEY: entry[PROGID_KEY], CALL_KEY: entry[CALL_KEY]}
                res[key] = {COUNT_KEY: 1, FIRST_APPEARANCE_KEY: value}
            else:
                res[key][COUNT_KEY] += 1

    return res


def find_repeated_pcs(function_pointers: list[dict]) -> dict[str, dict[str, dict]]:
    """
    Calculates dict GROUP-BY PC
    """
    first_appearances = find_first_appearance(function_pointers)
    return group_by_pc(first_appearances)

def group_by_pc(indexed_on_pair: dict[str, any]):
    """
    Does GROUP-BY PC on dict. Assumes entries have something 
    like "0xffffffff83a80e1f|0x0" as key, and anything as value.
    """    
    res = {}
    for pcStoredVal, value in indexed_on_pair.items():
        pc = pcStoredVal.split("|")[0]
        if pc not in res:
            res[pc] = {pcStoredVal: value}
        else:
            res[pc][pcStoredVal] = value
    return res


def categorize_appearances(
    function_pointers: list[dict], corpus_programs: list[dict]
) -> tuple[dict[str, dict], dict[str, dict]]:
    """
    finds among the first appearance of each PC|StoredValue, which was added to the corpus or not
    """
    first_appearances = find_first_appearance(function_pointers)
    added_to_corpus = category_was_added(corpus_programs, first_appearances)
    never_added = category_never_added(corpus_programs, first_appearances)
    return added_to_corpus, never_added


def category_was_added(corpus_programs, first_appearances):
    added_to_corpus = dict(
        (key, val)
        for key, val in first_appearances.items()
        if val[FIRST_APPEARANCE_KEY] in corpus_programs
    )
    return added_to_corpus


def category_never_added(corpus_programs, first_appearances):
    never_added = dict(
        (key, val)
        for key, val in first_appearances.items()
        if val[FIRST_APPEARANCE_KEY] not in corpus_programs
    )
    return never_added


def find_non_first_inclusion(
    function_pointers: list[dict], corpus_programs: list[dict]
) -> dict[str, dict]:
    never_added = category_never_added(
        corpus_programs, find_first_appearance(function_pointers)
    )

    monster_comprehension = dict(
        (
            f"{func[PC_KEY]}|{func[STORED_VALUE_KEY]}",
            {PROGID_KEY: entry[PROGID_KEY], CALL_KEY: entry[CALL_KEY]},
        )
        for entry in function_pointers
        for func in entry[FUNCTION_POINTERS_KEY]
        if (f"{func[PC_KEY]}|{func[STORED_VALUE_KEY]}" in never_added)
        and {PROGID_KEY: entry[PROGID_KEY], CALL_KEY: entry[CALL_KEY]}
        in corpus_programs
    )
    return monster_comprehension


def show_json_at(group_by_pc: dict, fname: str, order_by: callable) -> None:
    with open(fname, "w") as f:
        tmp = dict(sorted(group_by_pc.items(), reverse=True, key=order_by))
        json.dump(tmp, f, indent=4)
    print(f"Info: json dumped at " + fname)


def show_first_appearances(function_pointers: list[dict]) -> None:
    """
    dumps the calculated dict to a hardcoded json path
    """
    xx = find_first_appearance(function_pointers)
    print(f"Info: {len(xx)} distinct PC|StoredValue pairs.")
    dump_file_name = "analysis_results/first_appearances.json"
    show_json_at(xx, dump_file_name, order_by=lambda entry: entry[1][COUNT_KEY])


def show_appearances_categories(
    function_pointers: list[dict], corpus_programs: list[dict]
) -> None:
    added_to_corpus, never_added = categorize_appearances(
        function_pointers, corpus_programs
    )
    added_fname = "analysis_results/first_appearances_added_to_corpus.json"
    print(
        f"Info: {len(added_to_corpus)} programs that WERE ADDED to corpus and "
        + "are first find of <PC,StoredValue> pair"
    )
    show_category(added_to_corpus, added_fname)

    never_added_fname = "analysis_results/first_appearances_not_in_corpus.json"
    print(
        f"Info: {len(added_to_corpus)} programs that WERE NOT added to corpus and "
        + "are first find of <PC,StoredValue> pair"
    )
    show_category(never_added, never_added_fname)


def show_category(category_dict: dict[str, dict], filename: str) -> None:
    show_json_at(category_dict, filename, order_by=lambda entry: entry[1][COUNT_KEY])


def show_repeated_pcs(function_pointers: list[dict]) -> None:
    """
    dumps GROUP-BY PC dict to a hardcoded json file
    """
    group_by_pc = find_repeated_pcs(function_pointers)
    print(f"Info: {len(group_by_pc)} distinct PCs.")
    fname = "analysis_results/distinct_pcs.json"
    show_json_at(group_by_pc, fname, order_by=lambda key_val: len(key_val[1]))


def show_non_first_inclusions(
    function_pointers: list[dict], corpus_programs: list[dict]
) -> None:
    included_not_being_first = find_non_first_inclusion(function_pointers, corpus_programs)

    print(f"Info: {len(included_not_being_first)} things cover an edge repeatedly and were included.")

    fname = "analysis_results/added_in_second_round.json"
    res = group_by_pc(included_not_being_first)
    show_json_at(res, fname, order_by=lambda key_val: len(key_val[1]))


def check_exists(file: Path) -> None:
    if not file.exists():
        print(
            f"Error: The specified json file does not exist: {corpus_programs_path}",
            file=sys.stderr,
        )
        sys.exit(1)


def extract_json(file: Path) -> list[dict]:
    contents = file.read_text()
    return json.loads(contents)


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description="Parse a syzkaller log to extract corpus program additions."
    )
    parser.add_argument(
        "corpus_programs_path",
        type=str,
        nargs="?",
        help="Path to the json file with the programs that have been added to the corpus.",
    )
    parser.add_argument(
        "function_pointers_path",
        type=str,
        nargs="?",
        help="Path to the json file with the store instructions saving function pointers.",
    )
    args = parser.parse_args()

    if not args.corpus_programs_path or not args.function_pointers_path:
        parser.print_help()
        sys.exit(1)

    corpus_programs_path = Path(args.corpus_programs_path)
    function_pointers_path = Path(args.function_pointers_path)
    check_exists(corpus_programs_path)
    check_exists(function_pointers_path)

    corpus_programs = extract_json(corpus_programs_path)
    function_pointers = extract_json(function_pointers_path)

    # show_first_appearances(function_pointers)
    # show_appearances_categories(function_pointers, corpus_programs)
    # show_repeated_pcs(function_pointers)
    show_non_first_inclusions(function_pointers, corpus_programs)
