// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <arpa/inet.h>
#include <endian.h>
#include <errno.h>
#include <net/if.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/ioctl.h>

#define COVER_SIZE (64 << 10)
#define KCOV_TRACE_PC 0
#define KCOV_INIT_TRACE _IOR('c', 1, unsigned long)
#define KCOV_ENABLE _IO('c', 100)
#define KCOV_DISABLE _IO('c', 101)

#define KCOV_ENTRY_TYPE_HEADER_PC (0xdeadbeeffffffffeULL)
#define KCOV_ENTRY_TYPE_HEADER_FUN_POINTER (0xdeadbeefffffffffULL)

void process_kcov_buffer(unsigned long *cover) {
    unsigned long n, i;
    n = __atomic_load_n(&cover[0], __ATOMIC_RELAXED);
    printf("[*] KCOV Buffer recorded %lu words of trace data.\n", n);
    FILE *fout_pcs = fopen("syz_test_PCs.cov", "w");
    FILE *fout_FPs = fopen("syz_test_FPs.cov", "w");
    if (!fout_pcs || !fout_FPs) {
        perror("[-] Failed to open coverage files");
        return;
    }
    i = 1;
    while (i <= n) {
        unsigned long type = cover[i];
        if (type == KCOV_ENTRY_TYPE_HEADER_PC) {
            unsigned long pc = cover[i + 1];
            fprintf(fout_pcs, "0x%lx\n", pc);
            i += 2; 
        } else if (type == KCOV_ENTRY_TYPE_HEADER_FUN_POINTER) {
            unsigned long pc = cover[i + 1];
            unsigned long stored_value = cover[i + 3];
            fprintf(fout_FPs, "0x%lx 0x%lx\n", pc, stored_value);
            i += 4;
        } else {
            i += 1;
        }
    }
    fclose(fout_pcs);
    fclose(fout_FPs);    
    printf("[+] PC coverage data written to syz_test_PCs.cov\n");
    printf("[+] Function Pointer coverage data written to syz_test_FPs.cov\n");
}

int setup_kcov(unsigned long **cover) {
    int kcov_fd = open("/sys/kernel/debug/kcov", O_RDWR);
    if (kcov_fd == -1) { perror("[-] open kcov"); exit(1); }
    if (ioctl(kcov_fd, KCOV_INIT_TRACE, COVER_SIZE)) { perror("[-] ioctl init"); exit(1); }
    *cover = (unsigned long*)mmap(NULL, COVER_SIZE * sizeof(unsigned long), PROT_READ | PROT_WRITE, MAP_SHARED, kcov_fd, 0);
    if (*cover == MAP_FAILED) { perror("[-] mmap kcov"); exit(1); }
    if (ioctl(kcov_fd, KCOV_ENABLE, KCOV_TRACE_PC)) { perror("[-] ioctl enable"); exit(1); }
    __atomic_store_n(&(*cover)[0], 0, __ATOMIC_RELAXED);
    return kcov_fd;
}

void process_kcov_result(int kcov_fd, unsigned long *cover) {
    if (ioctl(kcov_fd, KCOV_DISABLE, 0)) { perror("[-] ioctl disable"); exit(1); }
    process_kcov_buffer(cover);
    munmap(cover, COVER_SIZE * sizeof(unsigned long));
    close(kcov_fd);
}
#include <linux/genetlink.h>
#include <linux/if_addr.h>
#include <linux/if_link.h>
#include <linux/in6.h>
#include <linux/neighbour.h>
#include <linux/net.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <linux/veth.h>

struct nlmsg {
	char* pos;
	int nesting;
	struct nlattr* nested[8];
	char buf[4096];
};

static void netlink_init(struct nlmsg* nlmsg, int typ, int flags,
			 const void* data, int size)
{
	memset(nlmsg, 0, sizeof(*nlmsg));
	struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
	hdr->nlmsg_type = typ;
	hdr->nlmsg_flags = NLM_F_REQUEST | NLM_F_ACK | flags;
	memcpy(hdr + 1, data, size);
	nlmsg->pos = (char*)(hdr + 1) + NLMSG_ALIGN(size);
}

static void netlink_attr(struct nlmsg* nlmsg, int typ,
			 const void* data, int size)
{
	struct nlattr* attr = (struct nlattr*)nlmsg->pos;
	attr->nla_len = sizeof(*attr) + size;
	attr->nla_type = typ;
	if (size > 0)
		memcpy(attr + 1, data, size);
	nlmsg->pos += NLMSG_ALIGN(attr->nla_len);
}

static int netlink_send_ext(struct nlmsg* nlmsg, int sock,
			    uint16_t reply_type, int* reply_len, bool dofail)
{
	if (nlmsg->pos > nlmsg->buf + sizeof(nlmsg->buf) || nlmsg->nesting)
	exit(1);
	struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
	hdr->nlmsg_len = nlmsg->pos - nlmsg->buf;
	struct sockaddr_nl addr;
	memset(&addr, 0, sizeof(addr));
	addr.nl_family = AF_NETLINK;
	ssize_t n = sendto(sock, nlmsg->buf, hdr->nlmsg_len, 0, (struct sockaddr*)&addr, sizeof(addr));
	if (n != (ssize_t)hdr->nlmsg_len) {
		if (dofail)
	exit(1);
		return -1;
	}
	n = recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
	if (reply_len)
		*reply_len = 0;
	if (n < 0) {
		if (dofail)
	exit(1);
		return -1;
	}
	if (n < (ssize_t)sizeof(struct nlmsghdr)) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	if (hdr->nlmsg_type == NLMSG_DONE)
		return 0;
	if (reply_len && hdr->nlmsg_type == reply_type) {
		*reply_len = n;
		return 0;
	}
	if (n < (ssize_t)(sizeof(struct nlmsghdr) + sizeof(struct nlmsgerr))) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	if (hdr->nlmsg_type != NLMSG_ERROR) {
		errno = EINVAL;
		if (dofail)
	exit(1);
		return -1;
	}
	errno = -((struct nlmsgerr*)(hdr + 1))->error;
	return -errno;
}

static int netlink_query_family_id(struct nlmsg* nlmsg, int sock, const char* family_name, bool dofail)
{
	struct genlmsghdr genlhdr;
	memset(&genlhdr, 0, sizeof(genlhdr));
	genlhdr.cmd = CTRL_CMD_GETFAMILY;
	netlink_init(nlmsg, GENL_ID_CTRL, 0, &genlhdr, sizeof(genlhdr));
	netlink_attr(nlmsg, CTRL_ATTR_FAMILY_NAME, family_name, strnlen(family_name, GENL_NAMSIZ - 1) + 1);
	int n = 0;
	int err = netlink_send_ext(nlmsg, sock, GENL_ID_CTRL, &n, dofail);
	if (err < 0) {
		return -1;
	}
	uint16_t id = 0;
	struct nlattr* attr = (struct nlattr*)(nlmsg->buf + NLMSG_HDRLEN + NLMSG_ALIGN(sizeof(genlhdr)));
	for (; (char*)attr < nlmsg->buf + n; attr = (struct nlattr*)((char*)attr + NLMSG_ALIGN(attr->nla_len))) {
		if (attr->nla_type == CTRL_ATTR_FAMILY_ID) {
			id = *(uint16_t*)(attr + 1);
			break;
		}
	}
	if (!id) {
		errno = EINVAL;
		return -1;
	}
	recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
	return id;
}

static long syz_genetlink_get_family_id(volatile long name, volatile long sock_arg)
{
	int fd = sock_arg;
	if (fd < 0) {
		fd = socket(AF_NETLINK, SOCK_RAW, NETLINK_GENERIC);
		if (fd == -1) {
			return -1;
		}
	}
	struct nlmsg nlmsg_tmp;
	int ret = netlink_query_family_id(&nlmsg_tmp, fd, (char*)name, false);
	if ((int)sock_arg < 0)
		close(fd);
	if (ret < 0) {
		return -1;
	}
	return ret;
}

uint64_t r[2] = {0xffffffffffffffff, 0x0};

int main(void)
{
		syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul, /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/0x32ul, /*fd=*/(intptr_t)-1, /*offset=*/0ul);
	syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul, /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/7ul, /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/0x32ul, /*fd=*/(intptr_t)-1, /*offset=*/0ul);
	syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul, /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/0x32ul, /*fd=*/(intptr_t)-1, /*offset=*/0ul);
	const char* reason;
	(void)reason;
				intptr_t res = 0;
	if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {}
//  socket$nl_generic arguments: [
//    domain: const = 0x10 (8 bytes)
//    type: const = 0x3 (8 bytes)
//    proto: const = 0x10 (4 bytes)
//  ]
//  returns sock_nl_generic
	res = syscall(__NR_socket, /*domain=*/0x10ul, /*type=*/3ul, /*proto=*/0x10);
	printf("socket() = %ld\n", res);
	if (res != -1)
		r[0] = res;
//  syz_genetlink_get_family_id$nl80211 arguments: [
//    name: ptr[in, buffer] {
//      buffer: {6e 6c 38 30 32 31 31 00} (length 0x8)
//    }
//    fd: sock_nl_generic (resource)
//  ]
//  returns nl80211_family_id
memcpy((void*)0x200000000040, "nl80211\000", 8);
	res = -1;
res = syz_genetlink_get_family_id(/*name=*/0x200000000040, /*fd=*/r[0]);
	printf("syz_genetlink_get_family_id() = %ld\n", res);
	if (res != -1)
		r[1] = res;
//  ioctl$sock_SIOCGIFINDEX_80211 arguments: [
//    fd: sock (resource)
//    cmd: const = 0x8933 (4 bytes)
//    arg: ptr[out, ifreq_dev_t[nl80211_devnames, nl80211_ifindex]] {
//      ifreq_dev_t[nl80211_devnames, nl80211_ifindex] {
//        ifr_ifrn: buffer: {77 6c 61 6e 30 00 00 00 00 00 00 00 00 00 00 00} (length 0x10)
//        elem: nl80211_ifindex (resource)
//        pad = 0x0 (20 bytes)
//      }
//    }
//  ]
memcpy((void*)0x200000000080, "wlan0\000\000\000\000\000\000\000\000\000\000\000", 16);
	res = syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x8933, /*arg=*/0x200000000080ul);
	printf("ioctl(SIOCGIFINDEX) = %ld\n", res);
//  sendmsg$NL80211_CMD_GET_KEY arguments: [
//    fd: sock_nl_generic (resource)
//    msg: ptr[in, msghdr_netlink[netlink_msg_t[nl80211_family_id, msg_nl80211_payload[NL80211_CMD_GET_KEY, nl80211_wdev_payload], nl80211_policy$cmd_key]]] {
//      msghdr_netlink[netlink_msg_t[nl80211_family_id, msg_nl80211_payload[NL80211_CMD_GET_KEY, nl80211_wdev_payload], nl80211_policy$cmd_key]] {
//        addr: nil
//        addrlen: len = 0x0 (4 bytes)
//        pad = 0x0 (4 bytes)
//        vec: ptr[in, iovec[in, netlink_msg_t[nl80211_family_id, msg_nl80211_payload[NL80211_CMD_GET_KEY, nl80211_wdev_payload], nl80211_policy$cmd_key]]] {
//          iovec[in, netlink_msg_t[nl80211_family_id, msg_nl80211_payload[NL80211_CMD_GET_KEY, nl80211_wdev_payload], nl80211_policy$cmd_key]] {
//            addr: ptr[in, netlink_msg_t[nl80211_family_id, msg_nl80211_payload[NL80211_CMD_GET_KEY, nl80211_wdev_payload], nl80211_policy$cmd_key]] {
//              netlink_msg_t[nl80211_family_id, msg_nl80211_payload[NL80211_CMD_GET_KEY, nl80211_wdev_payload], nl80211_policy$cmd_key] {
//                len: len = 0x1c (4 bytes)
//                type: nl80211_family_id (resource)
//                flags: netlink_msg_flags = 0x211 (2 bytes)
//                seq: int32 = 0x70bd25 (4 bytes)
//                pid: int32 = 0x25dfdbfb (4 bytes)
//                payload: msg_nl80211_payload[NL80211_CMD_GET_KEY, nl80211_wdev_payload] {
//                  genl_hdr: genlmsghdr_t[NL80211_CMD_GET_KEY] {
//                    cmd: const = 0x9 (1 bytes)
//                    version: const = 0x0 (1 bytes)
//                    reserved: const = 0x0 (2 bytes)
//                  }
//                  payload: nl80211_wdev_payload {
//                    NL80211_ATTR_IFINDEX: union optional[nlattr[NL80211_ATTR_IFINDEX, nl80211_ifindex]] {
//                      val: nlattr_t[const[NL80211_ATTR_IFINDEX, int16], nl80211_ifindex] {
//                        nla_len: offsetof = 0x0 (2 bytes)
//                        nla_type: const = 0x3 (2 bytes)
//                        payload: nl80211_ifindex (resource)
//                        size: buffer: {} (length 0x0)
//                      }
//                    }
//                    NL80211_ATTR_WDEV: union optional[nlattr[NL80211_ATTR_WDEV, nl80211_wdev]] {
//                      void: buffer: {} (length 0x0)
//                    }
//                  }
//                }
//                attrs: array[nl80211_policy$cmd_key] {
//                }
//              }
//            }
//            len: len = 0x1c (8 bytes)
//          }
//        }
//        vlen: const = 0x1 (8 bytes)
//        ctrl: const = 0x0 (8 bytes)
//        ctrllen: const = 0x0 (8 bytes)
//        f: send_flags = 0x8014 (4 bytes)
//        pad = 0x0 (4 bytes)
//      }
//    }
//    f: send_flags = 0x40844 (8 bytes)
//  ]
*(uint64_t*)0x2000000000c0 = 0;
*(uint32_t*)0x2000000000c8 = 0;
*(uint64_t*)0x2000000000d0 = 0x200000000100;
*(uint64_t*)0x200000000100 = 0x200000000140;
*(uint32_t*)0x200000000140 = 0x1c;
*(uint16_t*)0x200000000144 = r[1];
*(uint16_t*)0x200000000146 = 0x211;
*(uint32_t*)0x200000000148 = 0x70bd25;
*(uint32_t*)0x20000000014c = 0x25dfdbfb;
*(uint8_t*)0x200000000150 = 9;
*(uint8_t*)0x200000000151 = 0;
*(uint16_t*)0x200000000152 = 0;
*(uint16_t*)0x200000000154 = 0;
*(uint16_t*)0x200000000156 = 3;
*(uint32_t*)0x200000000158 = 0;
*(uint64_t*)0x200000000108 = 0x1c;
*(uint64_t*)0x2000000000d8 = 1;
*(uint64_t*)0x2000000000e0 = 0;
*(uint64_t*)0x2000000000e8 = 0;
*(uint32_t*)0x2000000000f0 = 0x8014;
	unsigned long *cover;
	int kcov_fd = setup_kcov(&cover);

	res = syscall(__NR_sendmsg, /*fd=*/r[0], /*msg=*/0x2000000000c0ul, /*f=MSG_BATCH|MSG_DONTWAIT|MSG_DONTROUTE|MSG_CONFIRM*/0x40844ul);
	printf("sendmsg() = %ld\n", res);

	process_kcov_result(kcov_fd, cover);
	return 0;
}
